### ISSUE TITLE
Package JEFFREY does not exist.

### ISSUE THREAD

**Issue by farooqkz** [ioannad/jeffrey#1]
```
* (jeffrey:random-graph 3 "out.png" "numbers")

debugger invoked on a SB-INT:SIMPLE-READER-PACKAGE-ERROR in thread
#<THREAD "main thread" RUNNING {1000560083}>:
  Package JEFFREY does not exist.

    Stream: #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDIN* {1000024B13}>

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE ] Use the current package, COMMON-LISP-USER.
  1: [RETRY    ] Retry finding the package.
  2: [USE-VALUE] Specify a different package
  3: [UNINTERN ] Read the symbol as uninterned.
  4: [SYMBOL   ] Specify a symbol to return
  5: [ABORT    ] Exit debugger, returning to top level.

(SB-IMPL::READER-FIND-PACKAGE "JEFFREY" #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDIN* {1000024B13}> T)
0] 
```
I have loaded the library with ql:quickload like this:
```
* (ql:quickload :jeffrey)
To load "jeffrey":
  Load 1 ASDF system:
    jeffrey
; Loading "jeffrey"
......
(:JEFFREY)
```
Also I'm using SBCL 2.0.1.debian and Quicklisp 2019-02-16.
I have installed jeffrey using `git clone repo_addr`.

**Comment by ioannad** [comment]
Sorry for the delay, @farooqkz, and thank you for finding this bug! 

There is no package `:jeffrey` listed in the [packages file](https://github.com/ioannad/jeffrey/blob/master/packages.lisp), the function `random-graph` is defined in the package `:jeffrey.main`. I should have clarified that in the README.md, but I now prefer to use `:jeffrey` instead, so I'm changing that in the next commit. Also it seems I forgot to export the function `random-graph` in that package (will fix at next commit).

Since unexported symbols must be referred to with double colon (`::`), this is currently the way to get such a graph:

```
(jeffrey.main::random-graph 3 "out" "numbers")
```

alternatively you could do:

```
(in-package :jeffrey.main)
(random-graph 3 "out" "numbers")
```

For either of these to work, please first create a directory `diagrams` in the repo root (bug I just found, tba in next commit). 

Also note that ".png" is added automatically, and unfortunately ignoring any existing ".png" ending. This should probably read the filename ending and figure out what encoding you want to use. I'll include that in the next commit as well (at it).

**Comment by farooqkz** [comment]
Very good :)
Please @ping me when you fixed these.

**Comment by farooqkz** [comment]
@ioannad Hello. You have not comitted anything yet.

**Comment by ioannad** [comment]
Hi @farooqkz sorry for the delay, I've been a bit pressed with time. I'll try to take care of it by the end of the week.

In case it wasn't clear in my last message, you could produce a "random-graph" diagram now by using:

```
(jeffrey.main::random-graph 3 "out" "numbers")
```

**Comment by farooqkz** [comment]
Okay and thanks. I'll wait.

**Comment by ioannad** [comment]
Hi @farooqkz and apologies for the delay. I just pushed a commit that fixes this issue, some other things I saw while I was at it, and to celebrate jeffrey's first issue, I added a long requested feature: graph-interval. ^^ 
Thank you for this and feel free to file more issues if you see something.

**Comment by farooqkz** [comment]
Thank you very much and no need for apologizing :)
